# Generated by Django 2.1.1 on 2021-07-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('id_number', models.CharField(max_length=191)),
                ('kra_pin', models.CharField(max_length=191)),
                ('email_address', models.CharField(max_length=191)),
                ('huduma_number', models.CharField(max_length=191)),
                ('profile_url', models.CharField(max_length=191)),
                ('date_of_graduation', models.CharField(max_length=191)),
                ('course', models.CharField(max_length=191)),
                ('file_url', models.CharField(max_length=191)),
                ('verified', models.BooleanField(default=True)),
                ('prev_hash', models.CharField(max_length=191)),
                ('file_name', models.CharField(max_length=191)),
                ('doc_hash', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=191)),
            ],
        ),
        migrations.AddField(
            model_name='documentblockmodel',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifier.Institution'),
        ),
    ]
