# Generated by Django 3.0 on 2021-07-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentblockmodel',
            name='doc_hash',
        ),
        migrations.RemoveField(
            model_name='documentblockmodel',
            name='prev_hash',
        ),
        migrations.AlterField(
            model_name='documentblockmodel',
            name='file_url',
            field=models.FileField(upload_to='docs'),
        ),
    ]
