# Generated by Django 4.2.30 on 2026-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0004_auto_20210705_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentblockmodel',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='documentblockmodel',
            name='classification',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='documentblockmodel',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='documentblockmodel',
            name='faculty_school',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='documentblockmodel',
            name='student_reg_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='documentblockmodel',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts'),
        ),
        migrations.AlterField(
            model_name='documentblockmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
